name: booking_reserv
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  flutter_multi_formatter: ^2.13.7
  go_router: ^15.1.2
  get_it: ^8.0.3
  intl: ^0.20.2
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/vectors/
    - assets/vectors/hide_password.svg
    - assets/vectors/show_password.svg
    - assets/vectors/back_icon.svg
