// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMra3Bh3hoXYH3ZPnyw8V4jYllynhggbM',
    appId: '1:259364057710:web:f51ce7d8c6c8bf26fc2c7f',
    messagingSenderId: '259364057710',
    projectId: 'bookingreserve-f2f4a',
    authDomain: 'bookingreserve-f2f4a.firebaseapp.com',
    storageBucket: 'bookingreserve-f2f4a.firebasestorage.app',
    measurementId: 'G-R53HZHN0F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwxaZWkV72JNfbNDlM4MFO3gGZ-IHjtEk',
    appId: '1:259364057710:android:bed3cff548d9ce4afc2c7f',
    messagingSenderId: '259364057710',
    projectId: 'bookingreserve-f2f4a',
    storageBucket: 'bookingreserve-f2f4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRWanc6OxkGidEhufTF9dOFhXLOetXG7c',
    appId: '1:259364057710:ios:e805f99d796935c5fc2c7f',
    messagingSenderId: '259364057710',
    projectId: 'bookingreserve-f2f4a',
    storageBucket: 'bookingreserve-f2f4a.firebasestorage.app',
    iosBundleId: 'com.example.bookingReserv',
  );
}
